//! Static-link bindings to librime + a thin safe wrapper.
//!
//! Raw bindings live in the `ffi` module (auto-generated by `bindgen` against
//! `rime_api_stdbool.h`). Everything above wraps the dispatch-via-struct API
//! so callers don't deal with raw pointers, `RIME_STRUCT_INIT`, or manual
//! `free_*` cleanup.

#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]
#![allow(dead_code)]
#![allow(clippy::missing_safety_doc)]

pub mod ffi {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

use std::ffi::{CStr, CString};
use std::mem::{self, MaybeUninit};
use std::os::raw::{c_char, c_int};
use std::path::Path;
use std::ptr;

pub use ffi::RimeSessionId;

/// Standard X11 keysym for the Backspace key — librime expects these for
/// non-printable input. Plain ASCII letters/digits go through as their
/// numeric value.
pub const KEY_BACKSPACE: i32 = 0xFF08;

/// Safe handle on the dispatch-via-struct librime API.
#[derive(Copy, Clone)]
pub struct Api {
    raw: *mut ffi::RimeApi_stdbool,
}

unsafe impl Send for Api {}
unsafe impl Sync for Api {}

/// Resolve a function pointer field on the API struct, panicking with the
/// field name if librime didn't populate it. Wraps the call in `unsafe`,
/// so `call!` invocations stay one-liners.
macro_rules! call {
    ($self:ident, $name:ident $(, $arg:expr)* $(,)?) => {{
        let f = unsafe { (*$self.raw).$name }
            .unwrap_or_else(|| panic!("librime API entry `{}` missing", stringify!($name)));
        unsafe { f($($arg),*) }
    }};
}

impl Api {
    /// Resolves `rime_get_api_stdbool()`. Returns `None` only if librime is
    /// missing the stdbool entrypoint — should never happen with a build
    /// driven by our own `build.rs`.
    pub fn get() -> Option<Self> {
        let raw = unsafe { ffi::rime_get_api_stdbool() };
        if raw.is_null() {
            None
        } else {
            Some(Self { raw })
        }
    }

    pub fn setup(&self, traits: &mut Traits) {
        call!(self, setup, &mut traits.inner);
    }

    pub fn initialize(&self, traits: &mut Traits) {
        call!(self, initialize, &mut traits.inner);
    }

    pub fn finalize(&self) {
        call!(self, finalize);
    }

    pub fn start_maintenance(&self, full_check: bool) -> bool {
        call!(self, start_maintenance, full_check)
    }

    pub fn join_maintenance_thread(&self) {
        call!(self, join_maintenance_thread);
    }

    pub fn create_session(&self) -> RimeSessionId {
        call!(self, create_session)
    }

    pub fn destroy_session(&self, sid: RimeSessionId) -> bool {
        call!(self, destroy_session, sid)
    }

    pub fn process_key(&self, sid: RimeSessionId, keycode: i32, mask: i32) -> bool {
        call!(self, process_key, sid, keycode as c_int, mask as c_int)
    }

    pub fn clear_composition(&self, sid: RimeSessionId) {
        call!(self, clear_composition, sid);
    }

    pub fn set_option(&self, sid: RimeSessionId, name: &str, value: bool) {
        let cname = CString::new(name).expect("option name has interior NUL");
        call!(self, set_option, sid, cname.as_ptr(), value);
    }

    pub fn change_page(&self, sid: RimeSessionId, backward: bool) -> bool {
        call!(self, change_page, sid, backward)
    }

    pub fn select_candidate_on_current_page(&self, sid: RimeSessionId, idx: usize) -> bool {
        call!(self, select_candidate_on_current_page, sid, idx)
    }

    pub fn highlight_candidate_on_current_page(&self, sid: RimeSessionId, idx: usize) -> bool {
        call!(self, highlight_candidate_on_current_page, sid, idx)
    }

    /// Drains the pending commit on `sid`. `None` if no commit is pending.
    pub fn get_commit(&self, sid: RimeSessionId) -> Option<String> {
        let mut commit = MaybeUninit::<ffi::RimeCommit>::zeroed();
        let p = commit.as_mut_ptr();
        unsafe { (*p).data_size = struct_data_size::<ffi::RimeCommit>() };
        if !call!(self, get_commit, sid, p) {
            return None;
        }
        let text = unsafe {
            if (*p).text.is_null() {
                None
            } else {
                Some(CStr::from_ptr((*p).text).to_string_lossy().into_owned())
            }
        };
        call!(self, free_commit, p);
        text.filter(|s| !s.is_empty())
    }

    /// Snapshot of the current input + menu. Strings are copied, so the
    /// returned struct is `'static`-safe.
    pub fn get_context(&self, sid: RimeSessionId) -> Option<Context> {
        let mut ctx = MaybeUninit::<ffi::RimeContext_stdbool>::zeroed();
        let p = ctx.as_mut_ptr();
        unsafe { (*p).data_size = struct_data_size::<ffi::RimeContext_stdbool>() };
        if !call!(self, get_context, sid, p) {
            return None;
        }
        let snapshot = unsafe {
            let composition = &(*p).composition;
            let preedit = cstr_to_string(composition.preedit);
            let composing = composition.length > 0 || !preedit.is_empty();

            let menu = &(*p).menu;
            let mut candidates = Vec::with_capacity(menu.num_candidates as usize);
            for i in 0..menu.num_candidates as isize {
                let c = &*menu.candidates.offset(i);
                candidates.push(Candidate {
                    text: cstr_to_string(c.text),
                    comment: cstr_to_string(c.comment),
                });
            }
            Context {
                composing,
                preedit,
                page_no: menu.page_no.max(0) as usize,
                is_last_page: menu.is_last_page,
                page_size: menu.page_size.max(0) as usize,
                highlighted: menu.highlighted_candidate_index.max(0) as usize,
                candidates,
            }
        };
        call!(self, free_context, p);
        Some(snapshot)
    }
}

/// Copied snapshot of `RimeContext_stdbool`. All strings are owned.
pub struct Context {
    pub composing: bool,
    pub preedit: String,
    pub page_no: usize,
    pub is_last_page: bool,
    pub page_size: usize,
    pub highlighted: usize,
    pub candidates: Vec<Candidate>,
}

#[derive(Clone)]
pub struct Candidate {
    pub text: String,
    pub comment: String,
}

/// Owned `RimeTraits`. Holds the C strings the inner struct points at so
/// they outlive every `setup`/`initialize` call that reads them.
pub struct Traits {
    inner: ffi::RimeTraits,
    _shared: CString,
    _user: CString,
    _name: CString,
    _code: CString,
    _version: CString,
    _app: CString,
    _log: CString,
}

impl Traits {
    pub fn new(shared_data_dir: &Path, user_data_dir: &Path) -> Self {
        let shared = path_to_cstring(shared_data_dir);
        let user = path_to_cstring(user_data_dir);
        let name = CString::new("zipin").unwrap();
        let code = CString::new("zipin").unwrap();
        let version = CString::new(env!("CARGO_PKG_VERSION")).unwrap();
        let app = CString::new("rime.zipin").unwrap();
        // log_dir = "" → librime keeps logs only on stderr, which is closed
        // anyway when ENABLE_LOGGING=OFF (our build flag).
        let log = CString::new("").unwrap();

        let mut inner: ffi::RimeTraits = unsafe { mem::zeroed() };
        inner.data_size = struct_data_size::<ffi::RimeTraits>();
        inner.shared_data_dir = shared.as_ptr();
        inner.user_data_dir = user.as_ptr();
        inner.distribution_name = name.as_ptr();
        inner.distribution_code_name = code.as_ptr();
        inner.distribution_version = version.as_ptr();
        inner.app_name = app.as_ptr();
        inner.modules = ptr::null_mut();
        inner.min_log_level = 3; // FATAL only
        inner.log_dir = log.as_ptr();
        inner.prebuilt_data_dir = ptr::null();
        inner.staging_dir = ptr::null();

        Self {
            inner,
            _shared: shared,
            _user: user,
            _name: name,
            _code: code,
            _version: version,
            _app: app,
            _log: log,
        }
    }
}

/// `RIME_STRUCT_INIT` macro: `data_size = sizeof(T) - sizeof(int)`.
fn struct_data_size<T>() -> c_int {
    (mem::size_of::<T>() - mem::size_of::<c_int>()) as c_int
}

fn cstr_to_string(p: *const c_char) -> String {
    if p.is_null() {
        String::new()
    } else {
        unsafe { CStr::from_ptr(p) }.to_string_lossy().into_owned()
    }
}

#[cfg(unix)]
fn path_to_cstring(p: &Path) -> CString {
    use std::os::unix::ffi::OsStrExt;
    CString::new(p.as_os_str().as_bytes()).expect("path contains NUL")
}

#[cfg(not(unix))]
fn path_to_cstring(p: &Path) -> CString {
    CString::new(p.to_string_lossy().as_bytes()).expect("path contains NUL")
}
